services:
  - docker

script:

  # Build
  - echo "Begin building Docker image"
  - docker build -t udagram-api-feed:v3 ./udagram-api-feed
  - docker build -t udagram-api-user:v3 ./udagram-api-user
  - docker build -t udagram-frontend:v3 ./udagram-frontend
  - docker build -t udagram-reverse-proxy:v3 ./udagram-reverse-proxy

  # Tagging
  - echo "Tagging Docker image"
  - docker tag udagram-api-feed:v3 $DOCKER_USERNAME/udagram-api-feed:v3  
  - docker tag udagram-api-user:v3 $DOCKER_USERNAME/udagram-api-user:v3  
  - docker tag udagram-frontend:v3 $DOCKER_USERNAME/udagram-frontend:v3
  - docker tag udagram-reverse-proxy:v3 $DOCKER_USERNAME/udagram-reverse-proxy:v3
  - echo "Docker images ls"
  - docker images ls

after_success:

  # Login Docker
  - echo "____LOGIN DOCKER____"
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - echo "____PUSH DOCKER IMAGES____"
  - docker push $DOCKER_USERNAME/udagram-api-feed:v3
  - docker push $DOCKER_USERNAME/udagram-api-user:v3  
  - docker push $DOCKER_USERNAME/udagram-frontend:v3  
  - docker push $DOCKER_USERNAME/udagram-reverse-proxy:v3  